CREATE DATABASE IF NOT EXISTS `rococo-auth`;
CREATE DATABASE IF NOT EXISTS `rococo-userdata`;
CREATE DATABASE IF NOT EXISTS `rococo-museum`;
CREATE DATABASE IF NOT EXISTS `rococo-artist`;
CREATE DATABASE IF NOT EXISTS `rococo-painting`;
CREATE DATABASE IF NOT EXISTS `rococo-geo`;
